name: 'A simple test workflow'

on: [push]

jobs:

    publish-image:

      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'gcloud-cli-setup'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'docker-credential-helper-setup'
        run: 'gcloud auth configure-docker ${{ vars.ARTEFACT_REGISTRY_HOSTNAME}}'

      - name: 'build-docker-image'
        run: 'docker build -t ${{ vars.APP_NAME }}:latest .; docker images | grep ${{ vars.APP_NAME }}'

      - name: 'tag-docker-image'
        run: 'docker tag ${{ vars.APP_NAME}}:latest ${{ vars.ARTEFACT_REGISTRY_ROOT}}/${{ vars.APP_NAME }}:latest'

      - name: 'gcloud-info'
        run: 'gcloud info'

      - name: 'gcloud-artefact-repos'
        run: 'gcloud artifacts repositories list'  

      - name: 'push-docker-image'
        run: 'docker push ${{ vars.ARTEFACT_REGISTRY_ROOT}}/${{ vars.APP_NAME }}:latest'

    deploy-cloud-run:
      needs: publish-image

      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2



      - name: 'terraform-plan'
        run: |
          cd terraform
          echo 1
          echo $GCP_CREDS | sed -E 's/[abcdefg]/!/g'
          echo 2
          echo $GCP_CREDS > credentials.json.base64
          echo 3
          ls -halt
          echo 4
          cat credentials.json.base64 | sed -E 's/[abcdefg]/!/g'
          echo 5
          openssl enc -base64 -d -in credentials.json.base64 -out credentials.json
          echo 6
          cat credentials.json
          echo 7
          ls -halt
        env:
          GCP_CREDS: ${{ secrets.GCP_CREDENTIALS }}
