name: Rob Test 
run-name: Rob Test
on: 
  pull_request:
    branches:
      - master

jobs:
  Test-Credentials:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "- Export Secret to credentials.json"
         echo '${{ secrets.ALT_CREDENTIAL_CONTENT }}' | base64 -d > credentials.json
         echo "- View the files in the current directory"
         ls -halt
         echo "- Change to the terraform directory"
         cd terraform
         echo "- Run terraform plan"
         terraform plan -var "SERVICE_NAME=MyServiceName" -var "DOCKER_IMAGE_LOCATION=google.com/something"