name: 'A simple test workflow'

on: [push]

jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
        - name: 'hello-world'
          run: echo ${{ vars.MY_HELLO_WORLD_VAR }}

    publish-container-image:
      runs-on: ubuntu-latest
      steps:
      - name: 'build-image'
        run: ls -lah