name: 'A simple test workflow'

on: [push]

env:
  MY_VAR: Example

jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
        - name: 'hello-world'
          run: echo ${{ env.MY_VAR }} 
          run: echo ${{ vars.ENVIRONMENT_NAME }}