name: 'A simple test workflow'

on: [push]

jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
        - name: 'hello-world'
          run: echo ${{ vars.MY_HELLO_WORLD_VAR }}

    job_id:
        runs-on: ubuntu-latest
        steps:
        - id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'

        - name: 'Use gcloud CLI'
          run: 'gcloud info'