name: Rob Test 
run-name: Rob Test 🚀
on: [push]
jobs:
  Test-Credentials:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo '${{ secrets.CREDENTIAL_CONTENT }}' | base64


         ewogICJ0***=